#!/usr/bin/env bash



set -e

nginx -c "$PWD/nginx.conf" &

# Apply database migrations
echo "Apply database migrations"
# # python manage.py makemigrations &

# python manage.py migrate &
# python /app/manage.py collectstatic --noinput &

# wait -n

#####################################################################################
# Options to DEBUG Django server
# Optional commands to replace abouve gunicorn command

# Option 1:
# run gunicorn with debug log level
# gunicorn server.wsgi --bind 0.0.0.0:8000 --workers 1 --threads 1 --log-level debug

# Option 2:
# run development server
# DEBUG=True ./manage.py runserver 0.0.0.0:8000