# Generated by Django 3.2.15 on 2023-04-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='odoo_customer_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
