
FROM node:lts-alpine as vue-build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
RUN npm i --silent
COPY . ./

RUN npm run build
FROM nginx:alpine
COPY nginx-local.conf /etc/nginx/conf.d/configfile.template

COPY --from=vue-build /app/dist /usr/share/nginx/html

CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"