#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

ls
pwd
# python manage.py makemigrations &
# python manage.py migrate &

# python manage.py createdata & 
# python manage.py collectstatic --noinput &


# python manage.py runserver_plus 0.0.0.0:8000 &
python manage.py runserver 0.0.0.0:8000 &


wait -n
